[package]
name    = "compacts"
version = "0.6.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
readme  = "README.md"
license = "Unlicense/MIT"
repository  = "https://github.com/feb29/compacts"
keywords    = ["compact", "succinct", "rank", "select"]
categories  = ["data-structures"]
description = "succinct data structures"
exclude = ["tests/*.bin"]

[dependencies]
byteorder   = "1"
itertools   = "0.6"

[dev-dependencies]
rand = "0.3"
quickcheck = "0.4"
