[package]
name    = "compacts"
version = "0.6.5"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
readme  = "README.md"
license = "Unlicense/MIT"
repository  = "https://github.com/feb29/compacts"
keywords    = ["succinct", "bitmap", "bitvec"]
categories  = ["data-structures"]
description = "succinct data structures"
exclude = ["tests/*.bin"]

[dependencies]
byteorder = "1"

[dev-dependencies]
quickcheck = "0.5"
rand = "0.3"
snap = "0.2"
zstd = "0.4"
