[package]
name    = "compacts"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
readme  = "README.md"
license = "MIT"
keywords    = ["compact", "succinct", "rank", "select"]
repository  = "https://github.com/feb29/compacts"
description = "compact data structures"

[dependencies]

[dependencies.num]
version = "0.1"

[dependencies.karabiner]
git = "https://github.com/feb29/karabiner"

[dev-dependencies]
log  = "0.3"
rand = "0.3"
env_logger = "0.4"
