[package]
name    = "compacts"
version = "0.7.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
readme  = "README.md"
license = "Unlicense/MIT"
exclude = ["tests/*.bin"]
repository  = "https://github.com/feb29/compacts"
keywords    = ["succinct", "bitmap", "bitvec", "bitset"]
categories  = ["data-structures"]
description = "succinct data structures"

[dependencies]
byteorder = "1"
lazy_static = "1"

[dev-dependencies]
quickcheck = "0.5"
rand = "0.4"
snap = "0.2"
zstd = "0.4"
