[package]
name    = "compacts"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
readme  = "README.md"
license = "MIT"
keywords    = ["compact", "succinct", "rank", "select"]
repository  = "https://github.com/feb29/compacts"
description = "succinct data structures"

[workspace]
members = [
  "compacts-prim",
  "compacts-bits",
  "compacts-dict"
]

[dependencies]
compacts-prim = { path = "./compacts-prim" }
compacts-bits = { path = "./compacts-bits" }
compacts-dict = { path = "./compacts-dict" }
