[package]
name    = "compacts"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
readme  = "README.md"
license = "MIT"
keywords = ["compact", "compressed", "succinct", "rank", "select", "dictionary"]

description = """compact dictionary"""
repository  = "https://github.com/feb29/compacts"

[dependencies.compacts-dict]
path = "compacts-dict"

[dependencies.compacts-bits]
path = "compacts-bits"

[dev-dependencies]
rand = "0.3"
log = "0.3"
env_logger = "0.4"
