[package]
name    = "compacts"
version = "0.3.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
readme  = "README.md"
license = "Unlicense/MIT"
repository  = "https://github.com/feb29/compacts"
keywords    = ["compact", "succinct", "rank", "select"]
categories  = ["data-structures"]
description = "succinct data structures"

[workspace]
members = [
  "compacts-bits",
]

[dependencies]
compacts-bits = { path = "./compacts-bits", version = "0.3" }
