[package]
name    = "compacts"
version = "0.3.1"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
readme  = "README.md"
license = "Unlicense/MIT"
repository  = "https://github.com/feb29/compacts"
keywords    = ["compact", "succinct", "rank", "select"]
categories  = ["data-structures"]
description = "succinct data structures"

[dependencies]
parking_lot = "0.4"
itertools   = "0.6"

[dev-dependencies]
log  = "0.3"
rand = "0.3"
env_logger = "0.4"
quickcheck = "0.4"
