[package]
name    = "cds"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]

[dependencies]
num = "0.1"
log = "0.3"

[dependencies.thunk]
path = "thunk"

[dev-dependencies]
rand = "0.3"
env_logger = "0.4"
