[package]
name    = "compacts"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
readme  = "README.md"
license = "MIT/Apache-2.0"
repository  = "https://github.com/feb29/compacts"
keywords    = ["compact", "succinct", "rank", "select"]
description = "succinct data structures"

[workspace]
members = [
  "compacts-prim",
  "compacts-bits",
  "compacts-dict"
]

[dependencies]
compacts-prim = { path = "./compacts-prim", version = "0.1" }
compacts-bits = { path = "./compacts-bits", version = "0.1" }
compacts-dict = { path = "./compacts-dict", version = "0.1" }
