[package]
name    = "compacts"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
readme  = "README.md"
license = "MIT"

keywords    = ["compact", "succinct", "rank", "select"]
repository  = "https://github.com/feb29/compacts"
description = "compact data structures"

[workspace]
members = ["thunk", "compacts-dict", "compacts-bits"]

[dependencies]
compacts-dict = { path = "compacts-dict" }
compacts-bits = { path = "compacts-bits" }

[dev-dependencies]
rand = "0.3"
