[package]
name    = "compacts-bits"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]

[dependencies]
log = "0.3"

[dependencies.thunk]
path = "../thunk"

[dependencies.compacts-dict]
path = "../compacts-dict"

[dev-dependencies]
rand = "0.3"
env_logger = "0.4"
