[package]
name    = "compacts-prim"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
license = "Unlicense/MIT"
repository  = "https://github.com/feb29/compacts"
keywords    = ["primitive"]
description = "trait for word"

[dependencies]
num = "0.1"
