[package]
name    = "compacts-prim"
version = "0.2.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
license = "Unlicense/MIT"
repository  = "https://github.com/feb29/compacts"
keywords    = ["primitive"]
description = "internal trait for compacts"

[dependencies]
